#%RAML 0.8

title: PutPut API
baseUri: https://www.putput.org
version: v1
schemas:
  - empty: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.Empty",
        "description": "A empty object",
        "properties": {
        }
      }

  - halLink: |
      {
        "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.HalLink",
        "description": "A HAL link",
        "properties": {
          "href":  { "type": "string" },
          "name": { "type": "string" },
          "type": { "type": "string" },
          "templated": {"type": "boolean"}
        }
      }

  - contactListLinks: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.ContactListLinks",
        "description": "The links of a contact list",
        "properties": {
          "self" : { "$ref": "halLink"}
        }
      }

  - contact: |
     {  "$schema": "http://json-schema.org/schema",
        "type": "object",
        "description": "A contact",
        "properties": {
            "id" : { "type": "string"},
            "firstName" : { "type": "string"},
            "lastName" : { "type": "string"},
            "additionalNames" : { "type": "string"},
            "salutation" : { "type": "string"},
            "dateOfBirth" : { "type": "number" },
            "anniversary" : { "type": "number" },
            "organisation" : { "type": "string"},
            "notes" : { "type": "string"},
            "version" : { "type": "integer"},
            "contactAddresses" : {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id" : { "type": "string"},
                  "type" : { "type": "string"},
                  "street" : { "type": "string"},
                  "houseNo" : { "type": "string"},
                  "poBox" : { "type": "string"},
                  "country" : { "type": "string"},
                  "city" : { "type": "string"},
                  "postalCode" : { "type": "string"}
                }
              }
            },
            "phoneNumbers" : {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id" : { "type": "string" },
                  "type" : { "type": "string"},
                  "number" : { "type": "string"}
                }
              }
            },
            "emails" : {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id" : { "type": "string" },
                  "type" : { "type": "string"},
                  "address" : { "type": "string"}
                }
              }
            },
            "internetIdentifiers" : {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id" : { "type": "string" },
                  "type" : { "type": "string"},
                  "idValue" : { "type": "string"}
                }
              }
            },
            "_links": {
              "$ref": "contactLinks"
            }
        }
     }

  - contactLinks: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.ContactLinks",
        "description": "The links of a contact",
        "properties": {
          "self" : { "$ref": "halLink"}
        }
      }

  - newContact: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "properties": {
          "firstName": { "type": "string" },
          "lastName": { "type": "string" },
          "email": { "type": "string" },
          "mobilePhone": { "type": "string" }
        }
      }
  - note: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "properties": {
          "id": {"type": "string"},
          "shortText": {"type": "string"},
          "content": {"type": "string"},
          "created": {"type": "number"},
          "updated": {"type": "number"},
          "version": {"type": "integer"},
          "_links": {
            "$ref": "noteLinks"
          }
        }
      }
  - noteLinks: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.NoteLinks",
        "description": "The links of a note",
        "properties": {
          "self" : { "$ref": "halLink"}
        }
      }
  - noteListLinks: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.NoteListLinks",
        "description": "The links of a note list",
        "properties": {
          "self" : { "$ref": "halLink"}
        }
      }
  - streamItemResource: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "type": "object",
        "javaType" : "org.putput.api.model.StreamItemResource",
        "properties": {
          "streamItem": {
            "$ref": "streamItem"
          },
          "markerInfo": {
            "$ref": "markerInfo"
          },
          "_links": {
            "$ref": "streamItemLinks"
          }
        }
      }
  - markerInfo: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "type": "object",
        "javaType" : "org.putput.api.model.MarkerInfo",
        "properties": {
          "dislikes": {"type": "number"},
          "isDislike": {"type": "boolean"},
          "isFavorite": {"type": "boolean"},
          "isLike": {"type": "boolean"},
          "isReadLater": {"type": "boolean"},
          "likes": {"type": "number"}
        }
      }
  - streamItem: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "type": "object",
        "javaType" : "org.putput.api.model.StreamItem",
        "properties": {
          "id": {"type": "string"},
          "creator": {"type": "string"},
          "source": {"type": "string"},
          "title": {"type": "string"},
          "content": {"type": "string"},
          "created": {"type": "number"}
        }
      }
  - newMarker: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "type": "object",
        "javaType" : "org.putput.api.model.NewMarker",
        "properties": {
          "itemId": {"type": "string"},
          "markerType": {"type": "string"}
        }
      }
  - newStreamItem: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "type": "object",
        "javaType" : "org.putput.api.model.NewStreamItem",
        "properties": {
          "source": {"type": "string"},
          "title": {"type": "string"},
          "content": {"type": "string"}
        }
      }
  - streamItemLinks: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.StreamItemLinks",
        "description": "The links of a stream item",
        "properties": {
          "self" : { "$ref": "halLink"},
          "delete" : { "$ref": "halLink"}
        }
      }
  - streamItemListLinks: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.StreamItemListLinks",
        "description": "The links of a stream item list",
        "properties": {
          "self" : { "$ref": "halLink"},
          "nextPage" : { "$ref": "halLink"}
        }
      }
  - tag: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "properties": {
          "id": {"type": "string"},
          "taggableId": {"type": "string"},
          "name": {"type": "string"},
          "text": {"type": "string"},
          "_links": {
            "$ref": "tagLinks"
          }
        }
      }
  - tagLinks: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.TagLinks",
        "description": "The links of a tag",
        "properties": {
          "self" : { "$ref": "halLink"}
        }
      }
  - tagListLinks: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.ContactListLinks",
        "description": "The links of a contact list",
        "properties": {
          "self" : { "$ref": "halLink"}
        }
      }
  - file: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "properties": {
          "id": {"type": "string"},
          "parentId": {"type": "string"},
          "storageId": {"type": "string"},
          "isDirectory": {"type": "boolean"},
          "name": {"type": "string"},
          "path": {"type": "string"},
          "mimeType": {"type": "string"},
          "size": {"type": "number"},
          "md5": {"type": "string"},
          "created": {"type": "number"},
          "updated": {"type": "number"},
          "version": {"type": "integer"},
          "_links": {
            "$ref": "fileLinks"
          }
        }
      }
  - fileLinks: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.FileLinks",
        "description": "The links of a file",
        "properties": {
          "self" : { "$ref": "halLink"},
          "content" : { "$ref": "halLink"},
          "tags" : { "$ref": "halLink"}
        }
      }
  - fileListLinks: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.FileListLinks",
        "description": "The links of a file list",
        "properties": {
          "self" : { "$ref": "halLink"}
        }
      }
  - userInfo: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "properties": {
          "displayName": {"type": "string"}
        }
      }

  - userSettings: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "properties": {
          "email": {"type": "string"}
        }
      }

  - userSettingsUpdate: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "properties": {
          "email": {"type": "string"},
          "password": {"type": "string"},
          "passwordRepeat": {"type": "string"}
        }
      }
  - profile: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "type": "object",
        "javaType" : "org.putput.api.model.UserProfile",
        "properties": {
          "profile": {
            "$ref": "profileInfo"
          },
          "following": {"type": "boolean"},
          "_links": {
            "$ref": "profileLinks"
          }
        }
      }
  - profileInfo: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "type": "object",
        "javaType" : "org.putput.api.model.ProfileInfo",
        "properties": {
          "about": {"type": "string"},
          "followers": {
             "type": "array",
             "items": {
               "$ref": "followShip"
             }
           },
          "following": {
            "type": "array",
            "items": {
              "$ref": "followShip"
            }
          },
          "itemCount": {
            "type": "integer"
          }
        }
      }
  - profileLinks: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "javaType" : "org.putput.api.model.ProfileLinks",
        "description": "The links of a profile",
        "properties": {
          "self" : { "$ref": "halLink"},
          "stream" : { "$ref": "halLink"},
          "follow" : { "$ref": "halLink"},
          "unfollow" : { "$ref": "halLink"}
        }
      }
  - followShip: |
      {
        "$schema": "http://json-schema.org/json-schema",
        "properties": {
          "follower": {"type": "string"},
          "followed": {"type": "string"}
        }
      }
  - serviceDocument: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "description": "The root links of the contact service",
        "properties": {
          "_links": {
            "type": "object",
            "javaType" : "org.putput.api.model.ServiceDocumentLinks",
            "properties": {
              "self" : { "$ref": "halLink"},
              "notes" : { "$ref": "halLink"},
              "note" : { "$ref": "halLink"},
              "files" : { "$ref": "halLink"},
              "file" : { "$ref": "halLink"},
              "contacts" : { "$ref": "halLink"},
              "contact" : { "$ref": "halLink"},
              "user" : { "$ref": "halLink"},
              "user-settings" : { "$ref": "halLink"},
              "login" : { "$ref": "halLink"},
              "logout" : { "$ref": "halLink"},
              "password-reset": { "$ref": "halLink"}
            }
          }
        }
      }

  - passwordReset: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "description": "A request for a new password",
        "properties": {
          "email": {
            "type": "string",
            "description": "the email of the user requesting a new password"
          }
        }
      }

traits:
  - halCollection:
      queryParameters:
        page:
          description: The page to retrieve
          type: number
      responses:
        200:
          body:
            application/hal+json:
              schema: |
                { "$schema": "http://json-schema.org/schema",
                  "id": "<<id>>",
                  "type": "object",
                  "javaType" : "<<collectionJavaType>>",
                  "description": "A HAL collection",
                  "properties": {
                    "count": {
                      "type": "integer"
                    },
                    "<<itemsProperty>>": {
                      "type": "array",
                      "items": {
                        "$ref": "<<itemSchema>>"
                      }
                    },
                    "_links": {
                      "$ref": "<<collectionLinks>>"
                    }
                  }
                }

/:
  get:
    responses:
      200:
        body:
          application/hal+json:
            schema: serviceDocument

/login:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          username:
            description: the user trying to login
            required: true
            type: string
          password:
            description: the password of the user
            required: true
            type: string

/logout:
  post:
    body:
      application/json:
        schema: empty

/contacts:
  get:
    is: [ halCollection: { id: contactList, collectionJavaType: org.putput.api.model.ContactList, itemsProperty: contacts, itemSchema: contact, collectionLinks: contactListLinks}]
  /import:
    post:
      body:
        application/octet-stream:
        text/vcard:
      responses:
        200:

/contact:
  post:
    body:
      application/json:
        schema: newContact
    responses:
      201:
        headers:
          Location:
  /{id}:
    get:
      responses:
        200:
          body:
            application/hal+json:
              schema: contact
    put:
      body:
        application/json:
          schema: contact
      responses:
        200:
    delete:
      responses:
        200:

/note:
  post:
    body:
      application/json:
        schema: note
    responses:
      201:
        headers:
          Location:
  /{id}:
    get:
      responses:
        200:
          body:
            application/hal+json:
              schema: note
    put:
      body:
        application/json:
          schema: note
      responses:
        200:
    delete:
      responses:
        200:

/notes:
  get:
    is: [ halCollection: { id: noteList, collectionJavaType: org.putput.api.model.NoteList, itemsProperty: notes, itemSchema: note, collectionLinks: noteListLinks}]

/file:
  /{id}:
    get:
      responses:
        404:
        200:
          body:
            application/hal+json:
              schema: file
    delete:
      responses:
        200:
    /content:
      get:
        queryParameters:
          disposition:
            description: A flag to signal that that a content disposition attachment header should be added
            type: boolean
            required: false
        responses:
          404:
          403:
          200:
            headers:
              Content-Disposition:
                required: false
            body:
              application/octet-stream:
    /tag:
      /{tagId}:
        delete:
          responses:
            200:
    /tags:
      get:
        is: [ halCollection: { id: tagList, collectionJavaType: org.putput.api.model.TagList, itemsProperty: tags, itemSchema: tag, collectionLinks: tagListLinks}]
      post:
        body:
          application/json:
            schema: tag
        responses:
          201:
            headers:
              Location:
/files:
  get:
    is: [ halCollection: { id: fileList, collectionJavaType: org.putput.api.model.FileList, itemsProperty: files, itemSchema: file, collectionLinks: fileListLinks}]
    queryParameters:
      parent:
        description: the parent folder to list files for
        type: string
        required: false
      tag:
        description: param to search only files tagged with specified text, disables parent parameter
        type: string
        required: false

/stream:
  get:
    is: [ halCollection: { id: streamItemList, collectionJavaType: org.putput.api.model.StreamItemList, itemsProperty: items, itemSchema: streamItemResource, collectionLinks: streamItemListLinks}]
    queryParameters:
      profile:
        type: string
        required: false
      type:
        description: the type of stream to receive
        type: string
        required: false
  /items:
    post:
      body:
        application/json:
          schema: newStreamItem
      responses:
        201:
          headers:
            Location:
  /item:
    /{id}:
      get:
        responses:
          200:
            body:
              application/hal+json:
                schema: streamItemResource
          404:
      delete:
        responses:
          200:
          400:

/marker:
  post:
    body:
      application/json:
        schema: newMarker
    responses:
        200:
  delete:
    queryParameters:
      itemId:
        type: string
        required: true
      markerType:
        type: string
        required: true
    responses:
      200:

/password_request:
  post:
    body:
      application/json:
        schema: passwordReset
    responses:
      204:
      400:
        description: "Bad Request, unable to reset password"

/profile:
  /{userName}:
    get:
      responses:
        200:
          body:
            application/hal+json:
              schema: profile
        404:
    /follow:
      post:
        responses:
          200:
      delete:
        responses:
          200:
/user:
  /info:
    get:
      responses:
        200:
          body:
            application/json:
              schema: userInfo
  /settings:
    get:
      responses:
        200:
          body:
            application/json:
              schema: userSettings
    put:
      body:
        application/json:
          schema: userSettingsUpdate
      responses:
        204: