CREATE TABLE PP_USER (
  _ID VARCHAR(40) NOT NULL PRIMARY KEY,
  _USERNAME VARCHAR (255) NOT NULL,
  _PASSWORD_HASH VARCHAR (255) NOT NULL
);

-- user: user; password: password
INSERT INTO PP_USER(_ID, _USERNAME, _PASSWORD_HASH) VALUES ('1', 'user', '$2a$10$NV4rlug0FGyW0UuivufxOetXnm7FeVgDGXbBmtajo6htdDl6g9bs.');