CREATE TABLE PP_FILE (
  _ID VARCHAR (40) NOT NULL PRIMARY KEY,
  _PATH VARCHAR (1024),
  _DATA TEXT NOT NULL,
  _TYPE VARCHAR (128) NOT NULL
);

CREATE TABLE PP_CONTACT_IMAGE (
  _CONTACT_ID VARCHAR (40) NOT NULL,
  _FILE_ID VARCHAR (40) NOT NULL
);

ALTER TABLE PP_CONTACT_IMAGE ADD FOREIGN KEY (_CONTACT_ID) REFERENCES PP_CONTACT(_ID);
ALTER TABLE PP_CONTACT_IMAGE ADD FOREIGN KEY (_FILE_ID) REFERENCES PP_FILE(_ID);
