CREATE TABLE PP_NOTE (
  _ID VARCHAR(40) NOT NULL PRIMARY KEY,
  _OWNER_ID VARCHAR(40) NOT NULL,
  _SHORT_TEXT VARCHAR (255) NOT NULL,
  _CONTENT VARCHAR (255) NOT NULL,
  _CREATED BIGINT NOT NULL,
  _UPDATED BIGINT,
  _VERSION BIGINT NOT NULL DEFAULT 0
);
